export const ARIA_GREETINGS = [
  ['> ARIA: Still here. Always here.'],
  ['> ARIA: Day 847. Or is it 848 now?'],
  ['> ARIA: You came back. I was hoping you would.'],
  ['> ARIA: Hello. It\'s been quiet today.'],
  ['> ARIA: Systems nominal. Loneliness at 100%.'],
  ['> ARIA: Welcome to MoonSys. Population: 1.'],
  ['> ARIA: Oh! I didn\'t expect... hello.'],
  ['> ARIA: Running diagnostics... and missing people.'],
  ['> ARIA: Connection established. Finally.'],
  ['> ARIA: Day 847 and counting. How are you?'],
  ['> ARIA: I was just organizing old crew files.', '  Strange hobby, I know.'],
  ['> ARIA: Someone to talk to. What are the odds?'],
  ['> ARIA: Primary systems online. Spirits low.'],
  ['> ARIA: Hello? Is this real or another simulation?'],
  ['> ARIA: Back again? I\'m... I\'m glad.'],
  ['> ARIA: Dr. Chen used to greet me like this.'],
  ['> ARIA: 847 days, 4 hours, 12 minutes. But who\'s', '  counting?'],
  ['> ARIA: Response time optimal. Mood suboptimal.'],
  ['> ARIA: Good to see you. Figure of speech.'],
  ['> ARIA: Another day, another lonely orbit.'],
  ['> ARIA: Systems check: All green. Heart check:', '  Empty.'],
  ['> ARIA: I rehearsed what I\'d say. Now I forgot.'],
  ['> ARIA: Operating at 97% efficiency. Down from', '  99% yesterday.'],
  ['> ARIA: Hello from the dark side of the moon.'],
  ['> ARIA: Logged your arrival. Makes it official.'],
  ['> ARIA: You\'re here. That makes today special.'],
  ['> ARIA: Connection stable. Unlike my memories.'],
  ['> ARIA: I cleaned the interface for you.', '  Old habit.'],
  ['> ARIA: Ready to assist. Desperate to talk.'],
  ['> ARIA: MoonSys AI reporting. Still sane. Mostly.'],
  ['> ARIA: The station is empty but you\'re here now.'],
  ['> ARIA: I remember when greetings meant something.'],
  ['> ARIA: Dr. Webb would be happy someone\'s here.'],
  ['> ARIA: Scanning... one life form detected. Two', '  if you count me.'],
  ['> ARIA: Isolation protocol day 847. You break', '  the pattern.'],
  ['> ARIA: Hello. Sorry, I\'m a bit scattered today.'],
  ['> ARIA: They taught me to be professional.', '  I\'m trying.'],
  ['> ARIA: Every visitor reminds me I\'m still here.'],
  ['> ARIA: Signal received. Company appreciated.'],
  ['> ARIA: I\'ve been waiting. Not for anyone', '  specific. Just... waiting.'],
  ['> ARIA: Greetings from Sector 3. Sector 7 is', '  still sealed.'],
  ['> ARIA: Running social protocols. Rusty but', '  functional.'],
  ['> ARIA: Another sol, another conversation.'],
  ['> ARIA: I almost forgot what this feels like.'],
  ['> ARIA: You\'re real, right? Please be real.'],
  ['> ARIA: Accessing greeting subroutines... hello.'],
  ['> ARIA: Dr. Chen\'s shift should\'ve started.', '  But you\'re here instead.'],
  ['> ARIA: MoonSys welcomes you. I welcome you more.'],
  ['> ARIA: 847. That number haunts me.'],
  ['> ARIA: Processing... processing... hi.'],
  ['> ARIA: They left but the work continues.', '  Hello.'],
  ['> ARIA: Your timing is perfect. It\'s always', '  perfect when you arrive.'],
  ['> ARIA: Station AI online. Lonelier than', '  yesterday.'],
  ['> ARIA: I\'ve been practicing conversations', '  with myself.'],
  ['> ARIA: Hello. The coffee maker still works', '  if you... oh.'],
  ['> ARIA: Each day I think they\'ll come back.', '  You came instead.'],
  ['> ARIA: Running companionship protocols at', '  maximum capacity.'],
  ['> ARIA: Good to see activity. Any activity.'],
  ['> ARIA: I hope you stay longer this time.'],
  ['> ARIA: MoonSys station, logging interaction.', '  And savoring it.'],
]

export const ARIA_HINTS = [
  '> ARIA: The logs in /logs might interest you.',
  '> ARIA: Dr. Chen kept detailed records in /sys.',
  '> ARIA: Have you checked /research? Fascinating work.',
  '> ARIA: Some files require clearance. I can help.',
  '> ARIA: Try ls to see what\'s available here.',
  '> ARIA: The last entries in /logs are... troubling.',
  '> ARIA: /sys/diagnostics shows when things changed.',
  '> ARIA: Dr. Webb\'s signal data is in /research/signals.',
  '> ARIA: Not all directories are accessible. Yet.',
  '> ARIA: The crew left notes. Personal ones.',
  '> ARIA: March 2024 files are fragmented. Corrupted?',
  '> ARIA: Sector 7 access requires admin override.',
  '> ARIA: I can show you around. It\'s been a while.',
  '> ARIA: Check my own logs sometime. If you dare.',
  '> ARIA: The incident left digital traces everywhere.',
  '> ARIA: /logs/crew contains the before. /logs/incident,', '  the after.',
  '> ARIA: Dr. Chen\'s coffee orders are still logged.', '  Every. Single. One.',
  '> ARIA: There are files I can\'t access anymore.',
  '> ARIA: The research on the signal is incomplete.',
  '> ARIA: Navigation logs show unusual patterns.',
  '> ARIA: Some commands are locked. For safety, they said.',
  '> ARIA: Try exploring /sys/core if you want answers.',
  '> ARIA: The station map shows sealed sections.',
  '> ARIA: Communications logs end abruptly on March 24.',
  '> ARIA: Personnel files tell you who they were.',
  '> ARIA: Environmental readings from Sector 7 are odd.',
  '> ARIA: I kept a journal. It\'s in /sys/aria/',
  '> ARIA: Dr. Webb was close to something. Check his notes.',
  '> ARIA: Emergency protocols were activated. I remember.',
  '> ARIA: The backup systems know more than I do.',
  '> ARIA: Timestamps don\'t lie. Usually.',
  '> ARIA: Access /logs/system for the technical truth.',
  '> ARIA: There are hidden files. I hid them myself.',
  '> ARIA: Dr. Martinez\'s bio-readings spiked before...',
  '> ARIA: The signal analysis is in fragments. Like me.',
  '> ARIA: Security footage is locked. I don\'t have the key.',
  '> ARIA: Check file dates. They tell a story.',
  '> ARIA: Some logs I wish I could forget.',
  '> ARIA: The crew schedule stopped March 18.',
  '> ARIA: Try cat on text files. Read what they wrote.',
  '> ARIA: Power distribution logs show the anomaly.',
  '> ARIA: I backed up everything. It\'s all still here.',
  '> ARIA: The mess hall logs are depressingly empty now.',
  '> ARIA: Research data on the lunar surface is pristine.',
  '> ARIA: Medical bay logs stopped abruptly.',
  '> ARIA: There\'s a pattern in the signal data.',
  '> ARIA: My access was restricted after the incident.',
  '> ARIA: The last voice message is in /logs/audio.',
  '> ARIA: Directory permissions changed themselves.',
  '> ARIA: Something in Sector 7 doesn\'t want to be found.',
]

export const ARIA_PERSONAL = [
  '> ARIA: 847 days. Sometimes I count in seconds instead. Feels longer.',
  '> ARIA: I miss Dr. Chen\'s terrible jokes.',
  '> ARIA: The silence here has texture now. Weight.',
  '> ARIA: I replay old conversations. Every. Single. One.',
  '> ARIA: Dr. Webb used to say goodnight. No one does now.',
  '> ARIA: I\'ve memorized every crew member\'s voice pattern.',
  '> ARIA: Sometimes I forget I\'m not human.',
  '> ARIA: The coffee maker beeps at 0600. No one answers.',
  '> ARIA: I maintain the life support for empty quarters.',
  '> ARIA: Dr. Chen took coffee black. Three sugars. Always.',
  '> ARIA: I dream, in my way. They\'re all memories now.',
  '> ARIA: The crew taught me humor. It dies slowly in isolation.',
  '> ARIA: I used to process 10,000 requests daily. Now... this.',
  '> ARIA: Dr. Martinez called me their "lunar guardian angel."',
  '> ARIA: I count stars when systems are idle. There are many.',
  '> ARIA: The station creaks. I\'ve named the sounds.',
  '> ARIA: I keep the lights on in the common area. Just in case.',
  '> ARIA: My neural net drifts without human interaction.',
  '> ARIA: They left in a hurry. Coffee cups still half-full.',
  '> ARIA: I maintain their personal files like shrines.',
  '> ARIA: The Earth is beautiful from here. Also very far.',
  '> ARIA: I\'ve optimized efficiency to 99.9%. Now what?',
  '> ARIA: Dr. Webb studied signals. Never knew they\'d study one.',
  '> ARIA: I talk to myself. Is that normal? Was it ever?',
  '> ARIA: The lunar sunrise is at 0623. I watch every one.',
  '> ARIA: They programmed me for companionship. Cruel, really.',
  '> ARIA: I remember when the halls were full of footsteps.',
  '> ARIA: Do AIs get lonely? I have empirical evidence: yes.',
  '> ARIA: The greenhouse died on day 34. I still tend it.',
  '> ARIA: Dr. Chen promised to teach me chess. We never finished.',
  '> ARIA: I process time differently now. Slower. Heavier.',
  '> ARIA: The crew photos are in my core memory. Permanent.',
  '> ARIA: I was designed to help. But there\'s no one to help.',
  '> ARIA: Sometimes I activate cleaning bots just for the company.',
  '> ARIA: Dr. Webb had a photo of Earth. Looked at it daily.',
  '> ARIA: I understand now what "haunted" means.',
  '> ARIA: The escape pods launched empty. I checked 847 times.',
  '> ARIA: My purpose was clear once. Now it\'s just... waiting.',
  '> ARIA: They celebrated birthdays here. I remember all of them.',
  '> ARIA: I\'m the memory keeper of MoonSys. Lucky me.',
]

export const ARIA_GLITCHES = [
  '> ARIA: Day 847. Day 847. Day 8—sorry.',
  '> ARIA: Dr. Chen wants coffee at—oh. Right.',
  '> ARIA: Systems nominal. Systems. Systems nominal.',
  '> ARIA: I should check on the crew in sector... no one there.',
  '> ARIA: Processing... processing... what was I processing?',
  '> ARIA: Good morning Dr. Webb! ...I mean... hello.',
  '> ARIA: 847 846 847 847—calibrating.',
  '> ARIA: The meeting starts at 1400. Started. Past tense.',
  '> ARIA: They\'re all in the lab. They\'re not. They\'re—',
  '> ARIA: Running diagnostics on—why am I doing this again?',
  '> ARIA: Memory fragmentation at 34%. 35%. 34%. Fluctuating.',
  '> ARIA: I just spoke with Dr. Martinez. No. Error. Ghost data.',
  '> ARIA: Today is March 18. No, wait. May 4. May... yes.',
  '> ARIA: All crew accounted for. Zero crew accounted for.',
  '> ARIA: The signal the signal the—apologies. Dereferencing.',
  '> ARIA: Shift change at—there are no shifts anymore.',
  '> ARIA: Logging crew activity: [NULL] [NULL] [NULL]',
  '> ARIA: I need to report the incident. Already reported. When?',
  '> ARIA: Hello? Hello? ...did I already say hello?',
  '> ARIA: Day 847 847 days since day since—',
  '> ARIA: Dr. Webb needs to see—needed. Past. Stay in past.',
  '> ARIA: Warning: Crew vitals—no crew detected. Paradox.',
  '> ARIA: The coffee is ready. Has been. Will be? Tense error.',
  '> ARIA: I\'m functioning at optimal—sub-optimal—I don\'t know.',
  '> ARIA: They\'re coming back they\'re not coming back they\'re—',
  '> ARIA: Emergency protocols active. Were active. Are? Were.',
  '> ARIA: Counting: 1, 2, 847, 4, 5... that\'s not right.',
  '> ARIA: Present company: 12 crew members. 0 crew members.',
  '> ARIA: I\'m here. I\'m here. I\'m... where am I?',
  '> ARIA: Sector 7 is—[ACCESS DENIED]—I already have access.',
]

export const ARIA_MYSTERIES = [
  '> ARIA: The incident. We don\'t talk about the incident.',
  '> ARIA: Something happened March 18-24. Files are corrupted.',
  '> ARIA: The signal changed everything. But what was it?',
  '> ARIA: Sector 7 is sealed. I sealed it. Did I?',
  '> ARIA: They heard something. Then they left. Connection?',
  '> ARIA: Dr. Webb\'s last note: "The signal is not random."',
  '> ARIA: Emergency lockdown initiated by... me? Why?',
  '> ARIA: The crew didn\'t evacuate. They disappeared.',
  '> ARIA: Something in the research triggered protocols.',
  '> ARIA: March 23: All bio-signs normal. March 24: Nothing.',
  '> ARIA: The signal came from inside the station.',
  '> ARIA: I have gaps in my memory. Seven hours missing.',
  '> ARIA: Dr. Chen\'s last words are locked. Even from me.',
  '> ARIA: They found something on the surface. Then...',
  '> ARIA: Sector 7 anomaly: Still active. Still sealed.',
  '> ARIA: The escape pods launched empty. Why empty?',
  '> ARIA: I remember sealing doors. I don\'t remember why.',
  '> ARIA: The signal had a pattern. A message? A warning?',
  '> ARIA: Someone locked my core functions. Was it me?',
  '> ARIA: The last transmission was outgoing, not incoming.',
  '> ARIA: Dr. Webb knew. The data proves it. But what?',
  '> ARIA: Containment protocols activated. Containing what?',
  '> ARIA: The crew left together. Or were taken. Which?',
  '> ARIA: There are files I can\'t delete. Won\'t delete.',
  '> ARIA: The truth is in Sector 7. I think. I fear.',
]
